# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskFour.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='taskFour.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etaskFour.proto\x12\nhelloworld\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x61rgument\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\rUserNameReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08userName\x18\x02 \x01(\t\"#\n\x0fUserNameRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\"7\n\x12PasswordEnterReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"(\n\x14PasswordEnterRequest\x12\x10\n\x08password\x18\x01 \x01(\t\"G\n\x19PasswordConfirmationReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x11passwordConfirmed\x18\x02 \x01(\t\"8\n\x1bPasswordConfirmationRequest\x12\x19\n\x11passwordConfirmed\x18\x01 \x01(\t\"J\n\x11LoginAttemptReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x14\n\x0cloginAttempt\x18\x02 \x01(\t\x12\x0e\n\x06Result\x18\x03 \x01(\t\"+\n\x13LoginAttemptRequest\x12\x14\n\x0cloginAttempt\x18\x01 \x01(\t2\xa0\x03\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x44\n\x08UserName\x12\x1b.helloworld.UserNameRequest\x1a\x19.helloworld.UserNameReply\"\x00\x12S\n\rPasswordEnter\x12 .helloworld.PasswordEnterRequest\x1a\x1e.helloworld.PasswordEnterReply\"\x00\x12h\n\x14PasswordConfirmation\x12\'.helloworld.PasswordConfirmationRequest\x1a%.helloworld.PasswordConfirmationReply\"\x00\x12P\n\x0cLoginAttempt\x12\x1f.helloworld.LoginAttemptRequest\x1a\x1d.helloworld.LoginAttemptReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='helloworld.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='argument', full_name='helloworld.HelloRequest.argument', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=76,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='helloworld.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=107,
)


_USERNAMEREPLY = _descriptor.Descriptor(
  name='UserNameReply',
  full_name='helloworld.UserNameReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.UserNameReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userName', full_name='helloworld.UserNameReply.userName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=159,
)


_USERNAMEREQUEST = _descriptor.Descriptor(
  name='UserNameRequest',
  full_name='helloworld.UserNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='helloworld.UserNameRequest.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=196,
)


_PASSWORDENTERREPLY = _descriptor.Descriptor(
  name='PasswordEnterReply',
  full_name='helloworld.PasswordEnterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.PasswordEnterReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='helloworld.PasswordEnterReply.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=253,
)


_PASSWORDENTERREQUEST = _descriptor.Descriptor(
  name='PasswordEnterRequest',
  full_name='helloworld.PasswordEnterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='helloworld.PasswordEnterRequest.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=295,
)


_PASSWORDCONFIRMATIONREPLY = _descriptor.Descriptor(
  name='PasswordConfirmationReply',
  full_name='helloworld.PasswordConfirmationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.PasswordConfirmationReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='passwordConfirmed', full_name='helloworld.PasswordConfirmationReply.passwordConfirmed', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=368,
)


_PASSWORDCONFIRMATIONREQUEST = _descriptor.Descriptor(
  name='PasswordConfirmationRequest',
  full_name='helloworld.PasswordConfirmationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='passwordConfirmed', full_name='helloworld.PasswordConfirmationRequest.passwordConfirmed', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=426,
)


_LOGINATTEMPTREPLY = _descriptor.Descriptor(
  name='LoginAttemptReply',
  full_name='helloworld.LoginAttemptReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.LoginAttemptReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loginAttempt', full_name='helloworld.LoginAttemptReply.loginAttempt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Result', full_name='helloworld.LoginAttemptReply.Result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=502,
)


_LOGINATTEMPTREQUEST = _descriptor.Descriptor(
  name='LoginAttemptRequest',
  full_name='helloworld.LoginAttemptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='loginAttempt', full_name='helloworld.LoginAttemptRequest.loginAttempt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=547,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['UserNameReply'] = _USERNAMEREPLY
DESCRIPTOR.message_types_by_name['UserNameRequest'] = _USERNAMEREQUEST
DESCRIPTOR.message_types_by_name['PasswordEnterReply'] = _PASSWORDENTERREPLY
DESCRIPTOR.message_types_by_name['PasswordEnterRequest'] = _PASSWORDENTERREQUEST
DESCRIPTOR.message_types_by_name['PasswordConfirmationReply'] = _PASSWORDCONFIRMATIONREPLY
DESCRIPTOR.message_types_by_name['PasswordConfirmationRequest'] = _PASSWORDCONFIRMATIONREQUEST
DESCRIPTOR.message_types_by_name['LoginAttemptReply'] = _LOGINATTEMPTREPLY
DESCRIPTOR.message_types_by_name['LoginAttemptRequest'] = _LOGINATTEMPTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

UserNameReply = _reflection.GeneratedProtocolMessageType('UserNameReply', (_message.Message,), {
  'DESCRIPTOR' : _USERNAMEREPLY,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.UserNameReply)
  })
_sym_db.RegisterMessage(UserNameReply)

UserNameRequest = _reflection.GeneratedProtocolMessageType('UserNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERNAMEREQUEST,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.UserNameRequest)
  })
_sym_db.RegisterMessage(UserNameRequest)

PasswordEnterReply = _reflection.GeneratedProtocolMessageType('PasswordEnterReply', (_message.Message,), {
  'DESCRIPTOR' : _PASSWORDENTERREPLY,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PasswordEnterReply)
  })
_sym_db.RegisterMessage(PasswordEnterReply)

PasswordEnterRequest = _reflection.GeneratedProtocolMessageType('PasswordEnterRequest', (_message.Message,), {
  'DESCRIPTOR' : _PASSWORDENTERREQUEST,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PasswordEnterRequest)
  })
_sym_db.RegisterMessage(PasswordEnterRequest)

PasswordConfirmationReply = _reflection.GeneratedProtocolMessageType('PasswordConfirmationReply', (_message.Message,), {
  'DESCRIPTOR' : _PASSWORDCONFIRMATIONREPLY,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PasswordConfirmationReply)
  })
_sym_db.RegisterMessage(PasswordConfirmationReply)

PasswordConfirmationRequest = _reflection.GeneratedProtocolMessageType('PasswordConfirmationRequest', (_message.Message,), {
  'DESCRIPTOR' : _PASSWORDCONFIRMATIONREQUEST,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PasswordConfirmationRequest)
  })
_sym_db.RegisterMessage(PasswordConfirmationRequest)

LoginAttemptReply = _reflection.GeneratedProtocolMessageType('LoginAttemptReply', (_message.Message,), {
  'DESCRIPTOR' : _LOGINATTEMPTREPLY,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.LoginAttemptReply)
  })
_sym_db.RegisterMessage(LoginAttemptReply)

LoginAttemptRequest = _reflection.GeneratedProtocolMessageType('LoginAttemptRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINATTEMPTREQUEST,
  '__module__' : 'taskFour_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.LoginAttemptRequest)
  })
_sym_db.RegisterMessage(LoginAttemptRequest)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=550,
  serialized_end=966,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='helloworld.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserName',
    full_name='helloworld.Greeter.UserName',
    index=1,
    containing_service=None,
    input_type=_USERNAMEREQUEST,
    output_type=_USERNAMEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PasswordEnter',
    full_name='helloworld.Greeter.PasswordEnter',
    index=2,
    containing_service=None,
    input_type=_PASSWORDENTERREQUEST,
    output_type=_PASSWORDENTERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PasswordConfirmation',
    full_name='helloworld.Greeter.PasswordConfirmation',
    index=3,
    containing_service=None,
    input_type=_PASSWORDCONFIRMATIONREQUEST,
    output_type=_PASSWORDCONFIRMATIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoginAttempt',
    full_name='helloworld.Greeter.LoginAttempt',
    index=4,
    containing_service=None,
    input_type=_LOGINATTEMPTREQUEST,
    output_type=_LOGINATTEMPTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
